---
Name: wedevelop-elastica
---
SilverStripe\Core\Injector\Injector:
  Elastica\Client:
    class: Elastica\Client
    constructor:
      config:
        host: '`ELASTICSEARCH_HOST`'
        port: '`ELASTICSEARCH_PORT`'

  Geocoder\Provider\Cache\ProviderCache.cache:
    factory: SilverStripe\Core\Cache\CacheFactory
  Geocoder\Geocoder:
    class: Geocoder\StatefulGeocoder
    constructor:
      0: '%$Geocoder\Provider\Cache\ProviderCache'

---
Name: wedevelop-elastica-auth
Only:
  envvarset:
    - ELASTICSEARCH_USERNAME
    - ELASTICSEARCH_PASSWORD
---
SilverStripe\Core\Injector\Injector:
  Elastica\Client:
    class: Elastica\Client
    constructor:
      config:
        username: '`ELASTICSEARCH_USERNAME`'
        password: '`ELASTICSEARCH_PASSWORD`'
