---
Name: elastica
---
SilverStripe\Core\Injector\Injector:
  ElasticaService:
    class: 'WeDevelop\Elastica\Services\ElasticaService'
    constructor:
      -
        host: '`ELASTICSEARCH_HOST`'
        port: '`ELASTICSEARCH_PORT`'
